import sys
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QSoundEffect
from PyQt5.QtCore import QUrl

font1 = "Trebuchet MS"
font2 = "Bahnschrift"

style_lampe = "QLabel{border-radius: 30px;border: 3px solid #32353A;color: #32353A;}"
style_lettre = "QPushButton { border-radius: 30px; border: 3px solid #BFBFC1; color: #BFBFC1; background: qradialgradient(spread:pad, cx:0.65, cy:0.65, radius:0.60, stop:0 #393B3F, stop:0.65 #393B3F, stop:0.66 #2D3033, stop:1 #2D3033); }QPushButton:Hover{background: qradialgradient(spread:pad, cx:0.66, cy:0.77, radius:0.70, stop:0 #242629, stop:0.65 #242629, stop:0.66 #242629, stop:1 #242629);}\n"
style_frame = "QFrame{border-radius: 7px;background-color: #2D3033;border: 2px solid #1A1C1E;}QFrame > *{border-radius: 0;border: none;background-color: transparent;}"
style_btn_r = "QPushButton{border: 2px solid #BFBFC1; border-radius: 7px; color: #BFBFC1; background: #282A2D}  QPushButton:Hover{background: #242629}"
style_border_r = "border: 2px solid #BFBFC1;border-radius: 7px;background: qlineargradient(y1:0, y2:1, stop:0 #1A1C1E,stop:0.30 transparent,stop:0.70 transparent,stop:1 #1A1C1E);\n"
style_position_r = "color: #BFBFC1;border-radius: 7px;background-color: #242629;"
style_label = "border-top: 2px solid #BFBFC1;border-left: 2px solid #BFBFC1;border-right: 2px solid #BFBFC1;border-top-left-radius: 7px;border-top-right-radius: 7px;color: #BFBFC1;"
style_entry = "border: 2px solid #BFBFC1;border-bottom-left-radius: 7px;border-bottom-right-radius: 7px;color: #BFBFC1;background-color: #242629;\n"
style_entry_crypte = "border: 2px solid #BFBFC1;border-radius: 7px;color: #BFBFC1;background-color: #242629;\n"

repertoire_actuel = os.path.dirname(os.path.abspath(__file__))
repertoire_root = os.path.dirname(os.path.dirname(repertoire_actuel))
repertoire_resources = os.path.join(repertoire_root, "data")

chemin_s_rotor = os.path.join(repertoire_resources, "sounds", "rotor.wav")
chemin_s_clavier = os.path.join(repertoire_resources, "sounds", "clavier.wav")
chemin_s_bouton = os.path.join(repertoire_resources, "sounds", "bouton.wav")

chemin_enigma_icon = os.path.join(repertoire_resources, "images", "enigma.png")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 650)
        MainWindow.setFixedSize(QtCore.QSize(1100, 650))
        MainWindow.setStyleSheet("background-color: #282A2D;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 10, 141, 211))
        self.logo.setStyleSheet(style_frame)
        self.logo.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.logo.setObjectName("logo")
        self.frame_lampe = QtWidgets.QFrame(self.centralwidget)
        self.frame_lampe.setGeometry(QtCore.QRect(160, 230, 931, 201))
        self.frame_lampe.setStyleSheet("QFrame{border-radius: 7px;border: 2px solid #1A1C1E;background: qlineargradient(spread:pad, x1:0, y1:0,x2:0, y2:0.06,stop:0 #1A1C1E, stop:1 #242629);}")
        self.frame_lampe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lampe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lampe.setObjectName("frame_lampe")
        self.lampe_l = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_l.setGeometry(QtCore.QRect(830, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_l.setFont(font)
        self.lampe_l.setStyleSheet(style_lampe)
        self.lampe_l.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_l.setObjectName("lampe_l")
        self.lampe_m = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_m.setGeometry(QtCore.QRect(730, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_m.setFont(font)
        self.lampe_m.setStyleSheet(style_lampe)
        self.lampe_m.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_m.setObjectName("lampe_m")
        self.lampe_t = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_t.setGeometry(QtCore.QRect(430, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_t.setFont(font)
        self.lampe_t.setStyleSheet(style_lampe)
        self.lampe_t.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_t.setObjectName("lampe_t")
        self.lampe_p = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_p.setGeometry(QtCore.QRect(30, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_p.setFont(font)
        self.lampe_p.setStyleSheet(style_lampe)
        self.lampe_p.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_p.setObjectName("lampe_p")
        self.lampe_h = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_h.setGeometry(QtCore.QRect(580, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_h.setFont(font)
        self.lampe_h.setStyleSheet(style_lampe)
        self.lampe_h.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_h.setObjectName("lampe_h")
        self.lampe_j = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_j.setGeometry(QtCore.QRect(680, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_j.setFont(font)
        self.lampe_j.setStyleSheet(style_lampe)
        self.lampe_j.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_j.setObjectName("lampe_j")
        self.lampe_u = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_u.setGeometry(QtCore.QRect(630, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_u.setFont(font)
        self.lampe_u.setStyleSheet(style_lampe)
        self.lampe_u.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_u.setObjectName("lampe_u")
        self.lampe_b = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_b.setGeometry(QtCore.QRect(530, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_b.setFont(font)
        self.lampe_b.setStyleSheet(style_lampe)
        self.lampe_b.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_b.setObjectName("lampe_b")
        self.lampe_c = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_c.setGeometry(QtCore.QRect(330, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_c.setFont(font)
        self.lampe_c.setStyleSheet(style_lampe)
        self.lampe_c.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_c.setObjectName("lampe_c")
        self.lampe_e = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_e.setGeometry(QtCore.QRect(230, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_e.setFont(font)
        self.lampe_e.setStyleSheet(style_lampe)
        self.lampe_e.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_e.setObjectName("lampe_e")
        self.lampe_o = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_o.setGeometry(QtCore.QRect(830, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_o.setFont(font)
        self.lampe_o.setStyleSheet(style_lampe)
        self.lampe_o.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_o.setObjectName("lampe_o")
        self.lampe_r = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_r.setGeometry(QtCore.QRect(330, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_r.setFont(font)
        self.lampe_r.setStyleSheet(style_lampe)
        self.lampe_r.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_r.setObjectName("lampe_r")
        self.lampe_v = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_v.setGeometry(QtCore.QRect(430, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_v.setFont(font)
        self.lampe_v.setStyleSheet(style_lampe)
        self.lampe_v.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_v.setObjectName("lampe_v")
        self.lampe_y = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_y.setGeometry(QtCore.QRect(130, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_y.setFont(font)
        self.lampe_y.setStyleSheet(style_lampe)
        self.lampe_y.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_y.setObjectName("lampe_y")
        self.lampe_q = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_q.setGeometry(QtCore.QRect(30, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_q.setFont(font)
        self.lampe_q.setStyleSheet(style_lampe)
        self.lampe_q.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_q.setObjectName("lampe_q")
        self.lampe_f = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_f.setGeometry(QtCore.QRect(380, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_f.setFont(font)
        self.lampe_f.setStyleSheet(style_lampe)
        self.lampe_f.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_f.setObjectName("lampe_f")
        self.lampe_d = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_d.setGeometry(QtCore.QRect(280, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_d.setFont(font)
        self.lampe_d.setStyleSheet(style_lampe)
        self.lampe_d.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_d.setObjectName("lampe_d")
        self.lampe_g = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_g.setGeometry(QtCore.QRect(480, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_g.setFont(font)
        self.lampe_g.setStyleSheet(style_lampe)
        self.lampe_g.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_g.setObjectName("lampe_g")
        self.lampe_s = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_s.setGeometry(QtCore.QRect(180, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_s.setFont(font)
        self.lampe_s.setStyleSheet(style_lampe)
        self.lampe_s.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_s.setObjectName("lampe_s")
        self.lampe_x = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_x.setGeometry(QtCore.QRect(230, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_x.setFont(font)
        self.lampe_x.setStyleSheet(style_lampe)
        self.lampe_x.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_x.setObjectName("lampe_x")
        self.lampe_i = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_i.setGeometry(QtCore.QRect(730, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_i.setFont(font)
        self.lampe_i.setStyleSheet(style_lampe)
        self.lampe_i.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_i.setObjectName("lampe_i")
        self.lampe_a = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_a.setGeometry(QtCore.QRect(80, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_a.setFont(font)
        self.lampe_a.setStyleSheet(style_lampe)
        self.lampe_a.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_a.setObjectName("lampe_a")
        self.lampe_k = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_k.setGeometry(QtCore.QRect(780, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_k.setFont(font)
        self.lampe_k.setStyleSheet(style_lampe)
        self.lampe_k.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_k.setObjectName("lampe_k")
        self.lampe_n = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_n.setGeometry(QtCore.QRect(630, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_n.setFont(font)
        self.lampe_n.setStyleSheet(style_lampe)
        self.lampe_n.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_n.setObjectName("lampe_n")
        self.lampe_w = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_w.setGeometry(QtCore.QRect(130, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_w.setFont(font)
        self.lampe_w.setStyleSheet(style_lampe)
        self.lampe_w.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_w.setObjectName("lampe_w")
        self.lampe_z = QtWidgets.QLabel(self.frame_lampe)
        self.lampe_z.setGeometry(QtCore.QRect(530, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lampe_z.setFont(font)
        self.lampe_z.setStyleSheet(style_lampe)
        self.lampe_z.setAlignment(QtCore.Qt.AlignCenter)
        self.lampe_z.setObjectName("lampe_z")
        self.frame_lettre = QtWidgets.QFrame(self.centralwidget)
        self.frame_lettre.setGeometry(QtCore.QRect(160, 440, 931, 201))
        self.frame_lettre.setStyleSheet(style_frame)
        self.frame_lettre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lettre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lettre.setObjectName("frame_lettre")
        self.lettre_q = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_q.setGeometry(QtCore.QRect(30, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_q.setFont(font)
        self.lettre_q.setStyleSheet(style_lettre)
        self.lettre_q.setObjectName("lettre_q")
        self.lettre_w = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_w.setGeometry(QtCore.QRect(130, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_w.setFont(font)
        self.lettre_w.setStyleSheet(style_lettre)
        self.lettre_w.setObjectName("lettre_w")
        self.lettre_e = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_e.setGeometry(QtCore.QRect(230, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_e.setFont(font)
        self.lettre_e.setStyleSheet(style_lettre)
        self.lettre_e.setObjectName("lettre_e")
        self.lettre_r = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_r.setGeometry(QtCore.QRect(330, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_r.setFont(font)
        self.lettre_r.setStyleSheet(style_lettre)
        self.lettre_r.setObjectName("lettre_r")
        self.lettre_t = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_t.setGeometry(QtCore.QRect(430, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_t.setFont(font)
        self.lettre_t.setStyleSheet(style_lettre)
        self.lettre_t.setObjectName("lettre_t")
        self.lettre_z = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_z.setGeometry(QtCore.QRect(530, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_z.setFont(font)
        self.lettre_z.setStyleSheet(style_lettre)
        self.lettre_z.setObjectName("lettre_z")
        self.lettre_u = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_u.setGeometry(QtCore.QRect(630, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_u.setFont(font)
        self.lettre_u.setStyleSheet(style_lettre)
        self.lettre_u.setObjectName("lettre_u")
        self.lettre_i = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_i.setGeometry(QtCore.QRect(730, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_i.setFont(font)
        self.lettre_i.setStyleSheet(style_lettre)
        self.lettre_i.setObjectName("lettre_i")
        self.lettre_o = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_o.setGeometry(QtCore.QRect(830, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_o.setFont(font)
        self.lettre_o.setStyleSheet(style_lettre)
        self.lettre_o.setObjectName("lettre_o")
        self.lettre_g = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_g.setGeometry(QtCore.QRect(480, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_g.setFont(font)
        self.lettre_g.setStyleSheet(style_lettre)
        self.lettre_g.setObjectName("lettre_g")
        self.lettre_d = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_d.setGeometry(QtCore.QRect(280, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_d.setFont(font)
        self.lettre_d.setStyleSheet(style_lettre)
        self.lettre_d.setObjectName("lettre_d")
        self.lettre_k = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_k.setGeometry(QtCore.QRect(780, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_k.setFont(font)
        self.lettre_k.setStyleSheet(style_lettre)
        self.lettre_k.setObjectName("lettre_k")
        self.lettre_h = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_h.setGeometry(QtCore.QRect(580, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_h.setFont(font)
        self.lettre_h.setStyleSheet(style_lettre)
        self.lettre_h.setObjectName("lettre_h")
        self.lettre_f = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_f.setGeometry(QtCore.QRect(380, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_f.setFont(font)
        self.lettre_f.setStyleSheet(style_lettre)
        self.lettre_f.setObjectName("lettre_f")
        self.lettre_a = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_a.setGeometry(QtCore.QRect(80, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_a.setFont(font)
        self.lettre_a.setStyleSheet(style_lettre)
        self.lettre_a.setObjectName("lettre_a")
        self.lettre_j = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_j.setGeometry(QtCore.QRect(680, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_j.setFont(font)
        self.lettre_j.setStyleSheet(style_lettre)
        self.lettre_j.setObjectName("lettre_j")
        self.lettre_s = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_s.setGeometry(QtCore.QRect(180, 70, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_s.setFont(font)
        self.lettre_s.setStyleSheet(style_lettre)
        self.lettre_s.setObjectName("lettre_s")
        self.lettre_b = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_b.setGeometry(QtCore.QRect(530, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_b.setFont(font)
        self.lettre_b.setStyleSheet(style_lettre)
        self.lettre_b.setObjectName("lettre_b")
        self.lettre_c = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_c.setGeometry(QtCore.QRect(330, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_c.setFont(font)
        self.lettre_c.setStyleSheet(style_lettre)
        self.lettre_c.setObjectName("lettre_c")
        self.lettre_l = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_l.setGeometry(QtCore.QRect(830, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_l.setFont(font)
        self.lettre_l.setStyleSheet(style_lettre)
        self.lettre_l.setObjectName("lettre_l")
        self.lettre_n = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_n.setGeometry(QtCore.QRect(630, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_n.setFont(font)
        self.lettre_n.setStyleSheet(style_lettre)
        self.lettre_n.setObjectName("lettre_n")
        self.lettre_v = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_v.setGeometry(QtCore.QRect(430, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_v.setFont(font)
        self.lettre_v.setStyleSheet(style_lettre)
        self.lettre_v.setObjectName("lettre_v")
        self.lettre_y = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_y.setGeometry(QtCore.QRect(130, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_y.setFont(font)
        self.lettre_y.setStyleSheet(style_lettre)
        self.lettre_y.setObjectName("lettre_y")
        self.lettre_p = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_p.setGeometry(QtCore.QRect(30, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_p.setFont(font)
        self.lettre_p.setStyleSheet(style_lettre)
        self.lettre_p.setObjectName("lettre_p")
        self.lettre_x = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_x.setGeometry(QtCore.QRect(230, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_x.setFont(font)
        self.lettre_x.setStyleSheet(style_lettre)
        self.lettre_x.setObjectName("lettre_x")
        self.lettre_m = QtWidgets.QPushButton(self.frame_lettre)
        self.lettre_m.setGeometry(QtCore.QRect(730, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.lettre_m.setFont(font)
        self.lettre_m.setStyleSheet(style_lettre)
        self.lettre_m.setObjectName("lettre_m")
        self.frame_rg = QtWidgets.QFrame(self.centralwidget)
        self.frame_rg.setGeometry(QtCore.QRect(160, 10, 81, 211))
        self.frame_rg.setStyleSheet(style_frame)
        self.frame_rg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rg.setObjectName("frame_rg")
        self.border_rg = QtWidgets.QFrame(self.frame_rg)
        self.border_rg.setGeometry(QtCore.QRect(20, 70, 41, 91))
        self.border_rg.setStyleSheet(style_border_r)
        self.border_rg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_rg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_rg.setObjectName("border_rg")
        self.position_rg = QtWidgets.QLabel(self.frame_rg)
        self.position_rg.setGeometry(QtCore.QRect(20, 70, 41, 91))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.position_rg.setFont(font)
        self.position_rg.setStyleSheet(style_position_r)
        self.position_rg.setAlignment(QtCore.Qt.AlignCenter)
        self.position_rg.setObjectName("position_rg")
        self.label_rg = QtWidgets.QLabel(self.frame_rg)
        self.label_rg.setGeometry(QtCore.QRect(0, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_rg.setFont(font)
        self.label_rg.setStyleSheet("color: #BFBFC1;\n")
        self.label_rg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rg.setObjectName("label_rg")
        self.btn_rg_s = QtWidgets.QPushButton(self.frame_rg)
        self.btn_rg_s.setGeometry(QtCore.QRect(20, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(14)
        self.btn_rg_s.setFont(font)
        self.btn_rg_s.setStyleSheet(style_btn_r)
        self.btn_rg_s.setObjectName("btn_rg_s")
        self.btn_rg_p = QtWidgets.QPushButton(self.frame_rg)
        self.btn_rg_p.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(14)
        self.btn_rg_p.setFont(font)
        self.btn_rg_p.setStyleSheet(style_btn_r)
        self.btn_rg_p.setObjectName("btn_rg_p")
        self.position_rg.raise_()
        self.border_rg.raise_()
        self.label_rg.raise_()
        self.btn_rg_s.raise_()
        self.btn_rg_p.raise_()
        self.frame_rc = QtWidgets.QFrame(self.centralwidget)
        self.frame_rc.setGeometry(QtCore.QRect(250, 10, 81, 211))
        self.frame_rc.setStyleSheet(style_frame)
        self.frame_rc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rc.setObjectName("frame_rc")
        self.border_rc = QtWidgets.QFrame(self.frame_rc)
        self.border_rc.setGeometry(QtCore.QRect(20, 70, 41, 91))
        self.border_rc.setStyleSheet(style_border_r)
        self.border_rc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_rc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_rc.setObjectName("border_rc")
        self.position_rc = QtWidgets.QLabel(self.frame_rc)
        self.position_rc.setGeometry(QtCore.QRect(20, 70, 41, 91))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.position_rc.setFont(font)
        self.position_rc.setStyleSheet(style_position_r)
        self.position_rc.setAlignment(QtCore.Qt.AlignCenter)
        self.position_rc.setObjectName("position_rc")
        self.label_rc = QtWidgets.QLabel(self.frame_rc)
        self.label_rc.setGeometry(QtCore.QRect(0, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_rc.setFont(font)
        self.label_rc.setStyleSheet("color: #BFBFC1;\n")
        self.label_rc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rc.setObjectName("label_rc")
        self.btn_rc_s = QtWidgets.QPushButton(self.frame_rc)
        self.btn_rc_s.setGeometry(QtCore.QRect(20, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(14)
        self.btn_rc_s.setFont(font)
        self.btn_rc_s.setStyleSheet(style_btn_r)
        self.btn_rc_s.setObjectName("btn_rc_s")
        self.btn_rc_p = QtWidgets.QPushButton(self.frame_rc)
        self.btn_rc_p.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(14)
        self.btn_rc_p.setFont(font)
        self.btn_rc_p.setStyleSheet(style_btn_r)
        self.btn_rc_p.setObjectName("btn_rc_p")
        self.position_rc.raise_()
        self.label_rc.raise_()
        self.border_rc.raise_()
        self.btn_rc_s.raise_()
        self.btn_rc_p.raise_()
        self.frame_rd = QtWidgets.QFrame(self.centralwidget)
        self.frame_rd.setGeometry(QtCore.QRect(340, 10, 81, 211))
        self.frame_rd.setStyleSheet(style_frame)
        self.frame_rd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rd.setObjectName("frame_rd")
        self.border_rd = QtWidgets.QFrame(self.frame_rd)
        self.border_rd.setGeometry(QtCore.QRect(20, 70, 41, 91))
        self.border_rd.setStyleSheet(style_border_r)
        self.border_rd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_rd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_rd.setObjectName("border_rd")
        self.position_rd = QtWidgets.QLabel(self.frame_rd)
        self.position_rd.setGeometry(QtCore.QRect(20, 70, 41, 91))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(26)
        self.position_rd.setFont(font)
        self.position_rd.setStyleSheet(style_position_r)
        self.position_rd.setAlignment(QtCore.Qt.AlignCenter)
        self.position_rd.setObjectName("position_rd")
        self.label_rd = QtWidgets.QLabel(self.frame_rd)
        self.label_rd.setGeometry(QtCore.QRect(0, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_rd.setFont(font)
        self.label_rd.setStyleSheet("color: #BFBFC1;\n")
        self.label_rd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rd.setObjectName("label_rd")
        self.btn_rd_s = QtWidgets.QPushButton(self.frame_rd)
        self.btn_rd_s.setGeometry(QtCore.QRect(20, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(14)
        self.btn_rd_s.setFont(font)
        self.btn_rd_s.setStyleSheet(style_btn_r)
        self.btn_rd_s.setObjectName("btn_rd_s")
        self.btn_rd_p = QtWidgets.QPushButton(self.frame_rd)
        self.btn_rd_p.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(14)
        self.btn_rd_p.setFont(font)
        self.btn_rd_p.setStyleSheet(style_btn_r)
        self.btn_rd_p.setObjectName("btn_rd_p")
        self.position_rd.raise_()
        self.label_rd.raise_()
        self.border_rd.raise_()
        self.btn_rd_s.raise_()
        self.btn_rd_p.raise_()
        self.frame_entry = QtWidgets.QFrame(self.centralwidget)
        self.frame_entry.setGeometry(QtCore.QRect(10, 230, 141, 411))
        self.frame_entry.setStyleSheet(style_frame)
        self.frame_entry.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_entry.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_entry.setObjectName("frame_entry")
        self.entry_non_crypte = QtWidgets.QPlainTextEdit(self.frame_entry)
        self.entry_non_crypte.setGeometry(QtCore.QRect(10, 230, 121, 171))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.entry_non_crypte.setFont(font)
        self.entry_non_crypte.setStyleSheet(style_entry_crypte)
        self.entry_non_crypte.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_non_crypte.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_non_crypte.setObjectName("entry_non_crypte")
        self.entry_non_crypte.setReadOnly(True)        
        self.entry_crypte = QtWidgets.QPlainTextEdit(self.frame_entry)
        self.entry_crypte.setGeometry(QtCore.QRect(10, 30, 121, 171))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.entry_crypte.setFont(font)
        self.entry_crypte.setStyleSheet(style_entry_crypte)
        self.entry_crypte.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_crypte.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_crypte.setObjectName("entry_crypte")
        self.entry_crypte.setReadOnly(True)
        self.label_crypte = QtWidgets.QLabel(self.frame_entry)
        self.label_crypte.setGeometry(QtCore.QRect(0, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_crypte.setFont(font)
        self.label_crypte.setStyleSheet("color: #BFBFC1;\n")
        self.label_crypte.setAlignment(QtCore.Qt.AlignCenter)
        self.label_crypte.setObjectName("label_crypte")
        self.label_non_crypte = QtWidgets.QLabel(self.frame_entry)
        self.label_non_crypte.setGeometry(QtCore.QRect(0, 200, 141, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_non_crypte.setFont(font)
        self.label_non_crypte.setStyleSheet("color: #BFBFC1;\n")
        self.label_non_crypte.setAlignment(QtCore.Qt.AlignCenter)
        self.label_non_crypte.setObjectName("label_non_crypte")
        self.frame_cablage = QtWidgets.QFrame(self.centralwidget)
        self.frame_cablage.setGeometry(QtCore.QRect(430, 10, 661, 211))
        self.frame_cablage.setStyleSheet(style_frame)
        self.frame_cablage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cablage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cablage.setObjectName("frame_cablage")
        self.a_label = QtWidgets.QLabel(self.frame_cablage)
        self.a_label.setGeometry(QtCore.QRect(10, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.a_label.setFont(font)
        self.a_label.setStyleSheet(style_label)
        self.a_label.setAlignment(QtCore.Qt.AlignCenter)
        self.a_label.setObjectName("a_label")
        self.a_entry = CustomLineEdit(self.frame_cablage)        
        self.a_entry.setGeometry(QtCore.QRect(10, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.a_entry.setFont(font)
        self.a_entry.setStyleSheet(style_entry)
        self.a_entry.setInputMask("")
        self.a_entry.setMaxLength(1)
        self.a_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.a_entry.setObjectName("a_entry")
        self.b_entry = CustomLineEdit(self.frame_cablage)
        self.b_entry.setGeometry(QtCore.QRect(60, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.b_entry.setFont(font)
        self.b_entry.setStyleSheet(style_entry)
        self.b_entry.setInputMask("")
        self.b_entry.setMaxLength(1)
        self.b_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.b_entry.setObjectName("b_entry")
        self.b_label = QtWidgets.QLabel(self.frame_cablage)
        self.b_label.setGeometry(QtCore.QRect(60, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.b_label.setFont(font)
        self.b_label.setStyleSheet(style_label)
        self.b_label.setAlignment(QtCore.Qt.AlignCenter)
        self.b_label.setObjectName("b_label")
        self.c_label = QtWidgets.QLabel(self.frame_cablage)
        self.c_label.setGeometry(QtCore.QRect(110, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.c_label.setFont(font)
        self.c_label.setStyleSheet(style_label)
        self.c_label.setAlignment(QtCore.Qt.AlignCenter)
        self.c_label.setObjectName("c_label")
        self.d_label = QtWidgets.QLabel(self.frame_cablage)
        self.d_label.setGeometry(QtCore.QRect(160, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.d_label.setFont(font)
        self.d_label.setStyleSheet(style_label)
        self.d_label.setAlignment(QtCore.Qt.AlignCenter)
        self.d_label.setObjectName("d_label")
        self.e_label = QtWidgets.QLabel(self.frame_cablage)
        self.e_label.setGeometry(QtCore.QRect(210, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.e_label.setFont(font)
        self.e_label.setStyleSheet(style_label)
        self.e_label.setAlignment(QtCore.Qt.AlignCenter)
        self.e_label.setObjectName("e_label")
        self.g_label = QtWidgets.QLabel(self.frame_cablage)
        self.g_label.setGeometry(QtCore.QRect(310, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.g_label.setFont(font)
        self.g_label.setStyleSheet(style_label)
        self.g_label.setAlignment(QtCore.Qt.AlignCenter)
        self.g_label.setObjectName("g_label")
        self.f_label = QtWidgets.QLabel(self.frame_cablage)
        self.f_label.setGeometry(QtCore.QRect(260, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.f_label.setFont(font)
        self.f_label.setStyleSheet(style_label)
        self.f_label.setAlignment(QtCore.Qt.AlignCenter)
        self.f_label.setObjectName("f_label")
        self.h_label = QtWidgets.QLabel(self.frame_cablage)
        self.h_label.setGeometry(QtCore.QRect(360, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.h_label.setFont(font)
        self.h_label.setStyleSheet(style_label)
        self.h_label.setAlignment(QtCore.Qt.AlignCenter)
        self.h_label.setObjectName("h_label")
        self.i_label = QtWidgets.QLabel(self.frame_cablage)
        self.i_label.setGeometry(QtCore.QRect(410, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.i_label.setFont(font)
        self.i_label.setStyleSheet(style_label)
        self.i_label.setAlignment(QtCore.Qt.AlignCenter)
        self.i_label.setObjectName("i_label")
        self.j_label = QtWidgets.QLabel(self.frame_cablage)
        self.j_label.setGeometry(QtCore.QRect(460, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.j_label.setFont(font)
        self.j_label.setStyleSheet(style_label)
        self.j_label.setAlignment(QtCore.Qt.AlignCenter)
        self.j_label.setObjectName("j_label")
        self.c_entry = CustomLineEdit(self.frame_cablage)
        self.c_entry.setGeometry(QtCore.QRect(110, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.c_entry.setFont(font)
        self.c_entry.setStyleSheet(style_entry)
        self.c_entry.setInputMask("")
        self.c_entry.setMaxLength(1)
        self.c_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.c_entry.setObjectName("c_entry")
        self.d_entry = CustomLineEdit(self.frame_cablage)
        self.d_entry.setGeometry(QtCore.QRect(160, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.d_entry.setFont(font)
        self.d_entry.setStyleSheet(style_entry)
        self.d_entry.setInputMask("")
        self.d_entry.setMaxLength(1)
        self.d_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.d_entry.setObjectName("d_entry")
        self.e_entry = CustomLineEdit(self.frame_cablage)
        self.e_entry.setGeometry(QtCore.QRect(210, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.e_entry.setFont(font)
        self.e_entry.setStyleSheet(style_entry)
        self.e_entry.setInputMask("")
        self.e_entry.setMaxLength(1)
        self.e_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.e_entry.setObjectName("e_entry")
        self.f_entry = CustomLineEdit(self.frame_cablage)
        self.f_entry.setGeometry(QtCore.QRect(260, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.f_entry.setFont(font)
        self.f_entry.setStyleSheet(style_entry)
        self.f_entry.setInputMask("")
        self.f_entry.setMaxLength(1)
        self.f_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.f_entry.setObjectName("f_entry")
        self.g_entry = CustomLineEdit(self.frame_cablage)
        self.g_entry.setGeometry(QtCore.QRect(310, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.g_entry.setFont(font)
        self.g_entry.setStyleSheet(style_entry)
        self.g_entry.setInputMask("")
        self.g_entry.setMaxLength(1)
        self.g_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.g_entry.setObjectName("g_entry")
        self.h_entry = CustomLineEdit(self.frame_cablage)
        self.h_entry.setGeometry(QtCore.QRect(360, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.h_entry.setFont(font)
        self.h_entry.setStyleSheet(style_entry)
        self.h_entry.setInputMask("")
        self.h_entry.setMaxLength(1)
        self.h_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.h_entry.setObjectName("h_entry")
        self.i_entry = CustomLineEdit(self.frame_cablage)
        self.i_entry.setGeometry(QtCore.QRect(410, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.i_entry.setFont(font)
        self.i_entry.setStyleSheet(style_entry)
        self.i_entry.setInputMask("")
        self.i_entry.setMaxLength(1)
        self.i_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.i_entry.setObjectName("i_entry")
        self.j_entry = CustomLineEdit(self.frame_cablage)
        self.j_entry.setGeometry(QtCore.QRect(460, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.j_entry.setFont(font)
        self.j_entry.setStyleSheet(style_entry)
        self.j_entry.setInputMask("")
        self.j_entry.setMaxLength(1)
        self.j_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.j_entry.setObjectName("j_entry")
        self.k_entry = CustomLineEdit(self.frame_cablage)
        self.k_entry.setGeometry(QtCore.QRect(510, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.k_entry.setFont(font)
        self.k_entry.setStyleSheet(style_entry)
        self.k_entry.setInputMask("")
        self.k_entry.setMaxLength(1)
        self.k_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.k_entry.setObjectName("k_entry")
        self.l_entry = CustomLineEdit(self.frame_cablage)
        self.l_entry.setGeometry(QtCore.QRect(560, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.l_entry.setFont(font)
        self.l_entry.setStyleSheet(style_entry)
        self.l_entry.setInputMask("")
        self.l_entry.setMaxLength(1)
        self.l_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.l_entry.setObjectName("l_entry")
        self.m_entry = CustomLineEdit(self.frame_cablage)
        self.m_entry.setGeometry(QtCore.QRect(610, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.m_entry.setFont(font)
        self.m_entry.setStyleSheet(style_entry)
        self.m_entry.setInputMask("")
        self.m_entry.setMaxLength(1)
        self.m_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.m_entry.setObjectName("m_entry")
        self.k_label = QtWidgets.QLabel(self.frame_cablage)
        self.k_label.setGeometry(QtCore.QRect(510, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.k_label.setFont(font)
        self.k_label.setStyleSheet(style_label)
        self.k_label.setAlignment(QtCore.Qt.AlignCenter)
        self.k_label.setObjectName("k_label")
        self.n_entry = CustomLineEdit(self.frame_cablage)
        self.n_entry.setGeometry(QtCore.QRect(10, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.n_entry.setFont(font)
        self.n_entry.setStyleSheet(style_entry)
        self.n_entry.setInputMask("")
        self.n_entry.setMaxLength(1)
        self.n_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.n_entry.setObjectName("n_entry")
        self.u_label = QtWidgets.QLabel(self.frame_cablage)
        self.u_label.setGeometry(QtCore.QRect(360, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.u_label.setFont(font)
        self.u_label.setStyleSheet(style_label)
        self.u_label.setAlignment(QtCore.Qt.AlignCenter)
        self.u_label.setObjectName("u_label")
        self.s_label = QtWidgets.QLabel(self.frame_cablage)
        self.s_label.setGeometry(QtCore.QRect(260, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.s_label.setFont(font)
        self.s_label.setStyleSheet(style_label)
        self.s_label.setAlignment(QtCore.Qt.AlignCenter)
        self.s_label.setObjectName("s_label")
        self.o_label = QtWidgets.QLabel(self.frame_cablage)
        self.o_label.setGeometry(QtCore.QRect(60, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.o_label.setFont(font)
        self.o_label.setStyleSheet(style_label)
        self.o_label.setAlignment(QtCore.Qt.AlignCenter)
        self.o_label.setObjectName("o_label")
        self.p_label = QtWidgets.QLabel(self.frame_cablage)
        self.p_label.setGeometry(QtCore.QRect(110, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.p_label.setFont(font)
        self.p_label.setStyleSheet(style_label)
        self.p_label.setAlignment(QtCore.Qt.AlignCenter)
        self.p_label.setObjectName("p_label")
        self.t_label = QtWidgets.QLabel(self.frame_cablage)
        self.t_label.setGeometry(QtCore.QRect(310, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.t_label.setFont(font)
        self.t_label.setStyleSheet(style_label)
        self.t_label.setAlignment(QtCore.Qt.AlignCenter)
        self.t_label.setObjectName("t_label")
        self.l_label = QtWidgets.QLabel(self.frame_cablage)
        self.l_label.setGeometry(QtCore.QRect(560, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.l_label.setFont(font)
        self.l_label.setStyleSheet(style_label)
        self.l_label.setAlignment(QtCore.Qt.AlignCenter)
        self.l_label.setObjectName("l_label")
        self.o_entry = CustomLineEdit(self.frame_cablage)
        self.o_entry.setGeometry(QtCore.QRect(60, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.o_entry.setFont(font)
        self.o_entry.setStyleSheet(style_entry)
        self.o_entry.setInputMask("")
        self.o_entry.setMaxLength(1)
        self.o_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.o_entry.setObjectName("o_entry")
        self.p_entry = CustomLineEdit(self.frame_cablage)
        self.p_entry.setGeometry(QtCore.QRect(110, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.p_entry.setFont(font)
        self.p_entry.setStyleSheet(style_entry)
        self.p_entry.setInputMask("")
        self.p_entry.setMaxLength(1)
        self.p_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.p_entry.setObjectName("p_entry")
        self.q_label = QtWidgets.QLabel(self.frame_cablage)
        self.q_label.setGeometry(QtCore.QRect(160, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.q_label.setFont(font)
        self.q_label.setStyleSheet(style_label)
        self.q_label.setAlignment(QtCore.Qt.AlignCenter)
        self.q_label.setObjectName("q_label")
        self.q_entry = CustomLineEdit(self.frame_cablage)
        self.q_entry.setGeometry(QtCore.QRect(160, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.q_entry.setFont(font)
        self.q_entry.setStyleSheet(style_entry)
        self.q_entry.setInputMask("")
        self.q_entry.setMaxLength(1)
        self.q_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.q_entry.setObjectName("q_entry")
        self.r_entry = CustomLineEdit(self.frame_cablage)
        self.r_entry.setGeometry(QtCore.QRect(210, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.r_entry.setFont(font)
        self.r_entry.setStyleSheet(style_entry)
        self.r_entry.setInputMask("")
        self.r_entry.setMaxLength(1)
        self.r_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.r_entry.setObjectName("r_entry")
        self.r_label = QtWidgets.QLabel(self.frame_cablage)
        self.r_label.setGeometry(QtCore.QRect(210, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.r_label.setFont(font)
        self.r_label.setStyleSheet(style_label)
        self.r_label.setAlignment(QtCore.Qt.AlignCenter)
        self.r_label.setObjectName("r_label")
        self.v_label = QtWidgets.QLabel(self.frame_cablage)
        self.v_label.setGeometry(QtCore.QRect(410, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.v_label.setFont(font)
        self.v_label.setStyleSheet(style_label)
        self.v_label.setAlignment(QtCore.Qt.AlignCenter)
        self.v_label.setObjectName("v_label")
        self.s_entry = CustomLineEdit(self.frame_cablage)
        self.s_entry.setGeometry(QtCore.QRect(260, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.s_entry.setFont(font)
        self.s_entry.setStyleSheet(style_entry)
        self.s_entry.setInputMask("")
        self.s_entry.setMaxLength(1)
        self.s_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.s_entry.setObjectName("s_entry")
        self.t_entry = CustomLineEdit(self.frame_cablage)
        self.t_entry.setGeometry(QtCore.QRect(310, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.t_entry.setFont(font)
        self.t_entry.setStyleSheet(style_entry)
        self.t_entry.setInputMask("")
        self.t_entry.setMaxLength(1)
        self.t_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.t_entry.setObjectName("t_entry")
        self.u_entry = CustomLineEdit(self.frame_cablage)
        self.u_entry.setGeometry(QtCore.QRect(360, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.u_entry.setFont(font)
        self.u_entry.setStyleSheet(style_entry)
        self.u_entry.setInputMask("")
        self.u_entry.setMaxLength(1)
        self.u_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.u_entry.setObjectName("u_entry")
        self.m_label = QtWidgets.QLabel(self.frame_cablage)
        self.m_label.setGeometry(QtCore.QRect(610, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.m_label.setFont(font)
        self.m_label.setStyleSheet(style_label)
        self.m_label.setAlignment(QtCore.Qt.AlignCenter)
        self.m_label.setObjectName("m_label")
        self.v_entry = CustomLineEdit(self.frame_cablage)
        self.v_entry.setGeometry(QtCore.QRect(410, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.v_entry.setFont(font)
        self.v_entry.setStyleSheet(style_entry)
        self.v_entry.setInputMask("")
        self.v_entry.setMaxLength(1)
        self.v_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.v_entry.setObjectName("v_entry")
        self.n_label = QtWidgets.QLabel(self.frame_cablage)
        self.n_label.setGeometry(QtCore.QRect(10, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.n_label.setFont(font)
        self.n_label.setStyleSheet(style_label)
        self.n_label.setAlignment(QtCore.Qt.AlignCenter)
        self.n_label.setObjectName("n_label")
        self.w_label = QtWidgets.QLabel(self.frame_cablage)
        self.w_label.setGeometry(QtCore.QRect(460, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.w_label.setFont(font)
        self.w_label.setStyleSheet(style_label)
        self.w_label.setAlignment(QtCore.Qt.AlignCenter)
        self.w_label.setObjectName("w_label")
        self.w_entry = CustomLineEdit(self.frame_cablage)
        self.w_entry.setGeometry(QtCore.QRect(460, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.w_entry.setFont(font)
        self.w_entry.setStyleSheet(style_entry)
        self.w_entry.setInputMask("")
        self.w_entry.setMaxLength(1)
        self.w_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.w_entry.setObjectName("w_entry")
        self.x_entry = CustomLineEdit(self.frame_cablage)
        self.x_entry.setGeometry(QtCore.QRect(510, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.x_entry.setFont(font)
        self.x_entry.setStyleSheet(style_entry)
        self.x_entry.setInputMask("")
        self.x_entry.setMaxLength(1)
        self.x_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.x_entry.setObjectName("x_entry")
        self.x_label = QtWidgets.QLabel(self.frame_cablage)
        self.x_label.setGeometry(QtCore.QRect(510, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.x_label.setFont(font)
        self.x_label.setStyleSheet(style_label)
        self.x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_label.setObjectName("x_label")
        self.label_cablage = QtWidgets.QLabel(self.frame_cablage)
        self.label_cablage.setGeometry(QtCore.QRect(0, 0, 661, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_cablage.setFont(font)
        self.label_cablage.setStyleSheet("color: #BFBFC1;\n""")
        self.label_cablage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cablage.setObjectName("label_cablage")
        self.y_entry = CustomLineEdit(self.frame_cablage)
        self.y_entry.setGeometry(QtCore.QRect(560, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.y_entry.setFont(font)
        self.y_entry.setStyleSheet(style_entry)
        self.y_entry.setInputMask("")
        self.y_entry.setMaxLength(1)
        self.y_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.y_entry.setObjectName("y_entry")
        self.y_label = QtWidgets.QLabel(self.frame_cablage)
        self.y_label.setGeometry(QtCore.QRect(560, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.y_label.setFont(font)
        self.y_label.setStyleSheet(style_label)
        self.y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_label.setObjectName("y_label")
        self.z_label = QtWidgets.QLabel(self.frame_cablage)
        self.z_label.setGeometry(QtCore.QRect(610, 120, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.z_label.setFont(font)
        self.z_label.setStyleSheet(style_label)
        self.z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.z_label.setObjectName("z_label")
        self.z_entry = CustomLineEdit(self.frame_cablage)
        self.z_entry.setGeometry(QtCore.QRect(610, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily(font1)
        font.setPointSize(20)
        self.z_entry.setFont(font)
        self.z_entry.setStyleSheet(style_entry)
        self.z_entry.setInputMask("")
        self.z_entry.setMaxLength(1)
        self.z_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.z_entry.setObjectName("z_entry")
        self.btn_configurer = QtWidgets.QPushButton(self.centralwidget)
        self.btn_configurer.setGeometry(QtCore.QRect(20, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_configurer.setFont(font)
        self.btn_configurer.setStyleSheet("QPushButton{border: 2px solid #BFBFC1; padding-bottom: 2px;border-radius: 7px;color: #BFBFC1;background: #242629;}QPushButton:Hover{border: 2px solid #8BB7B3;border-radius: 7px;background: qlineargradient(y1:0, y2:1, stop:0 rgba(139, 183, 179, 0.50),stop:0.30 rgba(139, 183, 179, 0.15),stop:0.70 rgba(139, 183, 179, 0.15),stop:1 rgba(139, 183, 179, 0.50));color: #8BB7B3;}")
        self.btn_configurer.setObjectName("btn_configurer")
        self.btn_reinitialiser = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reinitialiser.setGeometry(QtCore.QRect(20, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily(font2)
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_reinitialiser.setFont(font)
        self.btn_reinitialiser.setStyleSheet("QPushButton{border: 2px solid #BFBFC1; padding-bottom: 2px;border-radius: 7px;color: #BFBFC1;background: #242629;}QPushButton:Hover{border: 2px solid #8BB7B3;border-radius: 7px;background: qlineargradient(y1:0, y2:1, stop:0 rgba(139, 183, 179, 0.50),stop:0.30 rgba(139, 183, 179, 0.15),stop:0.70 rgba(139, 183, 179, 0.15),stop:1 rgba(139, 183, 179, 0.50));color: #8BB7B3;}")
        self.btn_reinitialiser.setObjectName("btn_reinitialiser")
        self.frame_rg.raise_()
        self.logo.raise_()
        self.frame_lampe.raise_()
        self.frame_lettre.raise_()
        self.frame_rc.raise_()
        self.frame_rd.raise_()
        self.frame_entry.raise_()
        self.frame_cablage.raise_()
        self.btn_reinitialiser.raise_()
        self.btn_configurer.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #----------------------------------------------------
        # IMPLEMENTATION DES FONCTIONNALITES
        #----------------------------------------------------

        # Connexion des lettres du clavier ------------------
        
        self.lettre_a.clicked.connect(lambda: self.verifier_touche("A"))
        self.lettre_b.clicked.connect(lambda: self.verifier_touche("B"))
        self.lettre_c.clicked.connect(lambda: self.verifier_touche("C"))
        self.lettre_d.clicked.connect(lambda: self.verifier_touche("D"))
        self.lettre_e.clicked.connect(lambda: self.verifier_touche("E"))
        self.lettre_f.clicked.connect(lambda: self.verifier_touche("F"))
        self.lettre_g.clicked.connect(lambda: self.verifier_touche("G"))
        self.lettre_h.clicked.connect(lambda: self.verifier_touche("H"))
        self.lettre_i.clicked.connect(lambda: self.verifier_touche("I"))
        self.lettre_j.clicked.connect(lambda: self.verifier_touche("J"))
        self.lettre_k.clicked.connect(lambda: self.verifier_touche("K"))
        self.lettre_l.clicked.connect(lambda: self.verifier_touche("L"))
        self.lettre_m.clicked.connect(lambda: self.verifier_touche("M"))
        self.lettre_n.clicked.connect(lambda: self.verifier_touche("N"))
        self.lettre_o.clicked.connect(lambda: self.verifier_touche("O"))
        self.lettre_p.clicked.connect(lambda: self.verifier_touche("P"))
        self.lettre_q.clicked.connect(lambda: self.verifier_touche("Q"))
        self.lettre_r.clicked.connect(lambda: self.verifier_touche("R"))
        self.lettre_s.clicked.connect(lambda: self.verifier_touche("S"))
        self.lettre_t.clicked.connect(lambda: self.verifier_touche("T"))
        self.lettre_u.clicked.connect(lambda: self.verifier_touche("U"))
        self.lettre_v.clicked.connect(lambda: self.verifier_touche("V"))
        self.lettre_w.clicked.connect(lambda: self.verifier_touche("W"))
        self.lettre_x.clicked.connect(lambda: self.verifier_touche("X"))
        self.lettre_y.clicked.connect(lambda: self.verifier_touche("Y"))
        self.lettre_z.clicked.connect(lambda: self.verifier_touche("Z"))

        # Detection des changements du cablage --------------

        self.a_entry.textChanged.connect(lambda: self.gerer_changement_cablage("A"))
        self.b_entry.textChanged.connect(lambda: self.gerer_changement_cablage("B"))
        self.c_entry.textChanged.connect(lambda: self.gerer_changement_cablage("C"))
        self.d_entry.textChanged.connect(lambda: self.gerer_changement_cablage("D"))
        self.e_entry.textChanged.connect(lambda: self.gerer_changement_cablage("E"))
        self.f_entry.textChanged.connect(lambda: self.gerer_changement_cablage("F"))
        self.g_entry.textChanged.connect(lambda: self.gerer_changement_cablage("G"))
        self.h_entry.textChanged.connect(lambda: self.gerer_changement_cablage("H"))
        self.i_entry.textChanged.connect(lambda: self.gerer_changement_cablage("I"))
        self.j_entry.textChanged.connect(lambda: self.gerer_changement_cablage("J"))
        self.k_entry.textChanged.connect(lambda: self.gerer_changement_cablage("K"))
        self.l_entry.textChanged.connect(lambda: self.gerer_changement_cablage("L"))
        self.m_entry.textChanged.connect(lambda: self.gerer_changement_cablage("M"))
        self.n_entry.textChanged.connect(lambda: self.gerer_changement_cablage("N"))
        self.o_entry.textChanged.connect(lambda: self.gerer_changement_cablage("O"))
        self.p_entry.textChanged.connect(lambda: self.gerer_changement_cablage("P"))
        self.q_entry.textChanged.connect(lambda: self.gerer_changement_cablage("Q"))
        self.r_entry.textChanged.connect(lambda: self.gerer_changement_cablage("R"))
        self.s_entry.textChanged.connect(lambda: self.gerer_changement_cablage("S"))
        self.t_entry.textChanged.connect(lambda: self.gerer_changement_cablage("T"))
        self.u_entry.textChanged.connect(lambda: self.gerer_changement_cablage("U"))
        self.v_entry.textChanged.connect(lambda: self.gerer_changement_cablage("V"))
        self.w_entry.textChanged.connect(lambda: self.gerer_changement_cablage("W"))
        self.x_entry.textChanged.connect(lambda: self.gerer_changement_cablage("X"))
        self.y_entry.textChanged.connect(lambda: self.gerer_changement_cablage("Y"))
        self.z_entry.textChanged.connect(lambda: self.gerer_changement_cablage("Z"))

        # Implementation des sons ---------------------------

        self.s_rotor = QSoundEffect()
        self.s_rotor.setSource(QUrl.fromLocalFile(chemin_s_rotor))
        self.s_rotor.setVolume(1.0)

        self.s_clavier = QSoundEffect()
        self.s_clavier.setSource(QUrl.fromLocalFile(chemin_s_clavier))
        self.s_clavier.setVolume(1.0)

        self.s_bouton = QSoundEffect()
        self.s_bouton.setSource(QUrl.fromLocalFile(chemin_s_bouton))
        self.s_bouton.setVolume(1.0)

        # Connexion des boutons -----------------------------

        self.btn_reinitialiser.clicked.connect(self.reinitialiser_machine)
        self.btn_configurer.clicked.connect(self.dialogue_config)
        
        self.btn_rg_p.clicked.connect(lambda: self.changer_lettre_initiale(self.position_rg, "precedent", "gauche"))
        self.btn_rg_s.clicked.connect(lambda: self.changer_lettre_initiale(self.position_rg, "suivant", "gauche"))

        self.btn_rc_p.clicked.connect(lambda: self.changer_lettre_initiale(self.position_rc, "precedent", "centre"))
        self.btn_rc_s.clicked.connect(lambda: self.changer_lettre_initiale(self.position_rc, "suivant", "centre"))

        self.btn_rd_p.clicked.connect(lambda: self.changer_lettre_initiale(self.position_rd, "precedent", "droite"))
        self.btn_rd_s.clicked.connect(lambda: self.changer_lettre_initiale(self.position_rd, "suivant", "droite"))

        # Definition des variables --------------------------

        self.alphabet = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
        self.dico_cablage = {}
        
        self.lettre_init_g = "A"
        self.lettre_init_c = "A"
        self.lettre_init_d = "A"
        
        self.dico_associations_lettres = {
            "A": [self.lettre_a, self.lampe_a, self.a_label, self.a_entry],
            "B": [self.lettre_b, self.lampe_b, self.b_label, self.b_entry],
            "C": [self.lettre_c, self.lampe_c, self.c_label, self.c_entry],
            "D": [self.lettre_d, self.lampe_d, self.d_label, self.d_entry],
            "E": [self.lettre_e, self.lampe_e, self.e_label, self.e_entry],
            "F": [self.lettre_f, self.lampe_f, self.f_label, self.f_entry],
            "G": [self.lettre_g, self.lampe_g, self.g_label, self.g_entry],
            "H": [self.lettre_h, self.lampe_h, self.h_label, self.h_entry],
            "I": [self.lettre_i, self.lampe_i, self.i_label, self.i_entry],
            "J": [self.lettre_j, self.lampe_j, self.j_label, self.j_entry],
            "K": [self.lettre_k, self.lampe_k, self.k_label, self.k_entry],
            "L": [self.lettre_l, self.lampe_l, self.l_label, self.l_entry],
            "M": [self.lettre_m, self.lampe_m, self.m_label, self.m_entry],
            "N": [self.lettre_n, self.lampe_n, self.n_label, self.n_entry],
            "O": [self.lettre_o, self.lampe_o, self.o_label, self.o_entry],
            "P": [self.lettre_p, self.lampe_p, self.p_label, self.p_entry],
            "Q": [self.lettre_q, self.lampe_q, self.q_label, self.q_entry],
            "R": [self.lettre_r, self.lampe_r, self.r_label, self.r_entry],
            "S": [self.lettre_s, self.lampe_s, self.s_label, self.s_entry],
            "T": [self.lettre_t, self.lampe_t, self.t_label, self.t_entry],
            "U": [self.lettre_u, self.lampe_u, self.u_label, self.u_entry],
            "V": [self.lettre_v, self.lampe_v, self.v_label, self.v_entry],
            "W": [self.lettre_w, self.lampe_w, self.w_label, self.w_entry],
            "X": [self.lettre_x, self.lampe_x, self.x_label, self.x_entry],
            "Y": [self.lettre_y, self.lampe_y, self.y_label, self.y_entry],
            "Z": [self.lettre_z, self.lampe_z, self.z_label, self.z_entry]}

    #----------------------------------------------------
    # METHODES
    #----------------------------------------------------

    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Machine Enigma M3"))
        self.logo.setPixmap(QtGui.QPixmap(chemin_enigma_icon))
        self.lampe_l.setText(_translate("MainWindow", "L"))
        self.lampe_m.setText(_translate("MainWindow", "M"))
        self.lampe_t.setText(_translate("MainWindow", "T"))
        self.lampe_p.setText(_translate("MainWindow", "P"))
        self.lampe_h.setText(_translate("MainWindow", "H"))
        self.lampe_j.setText(_translate("MainWindow", "J"))
        self.lampe_u.setText(_translate("MainWindow", "U"))
        self.lampe_b.setText(_translate("MainWindow", "B"))
        self.lampe_c.setText(_translate("MainWindow", "C"))
        self.lampe_e.setText(_translate("MainWindow", "E"))
        self.lampe_o.setText(_translate("MainWindow", "O"))
        self.lampe_r.setText(_translate("MainWindow", "R"))
        self.lampe_v.setText(_translate("MainWindow", "V"))
        self.lampe_y.setText(_translate("MainWindow", "Y"))
        self.lampe_q.setText(_translate("MainWindow", "Q"))
        self.lampe_f.setText(_translate("MainWindow", "F"))
        self.lampe_d.setText(_translate("MainWindow", "D"))
        self.lampe_g.setText(_translate("MainWindow", "G"))
        self.lampe_s.setText(_translate("MainWindow", "S"))
        self.lampe_x.setText(_translate("MainWindow", "X"))
        self.lampe_i.setText(_translate("MainWindow", "I"))
        self.lampe_a.setText(_translate("MainWindow", "A"))
        self.lampe_k.setText(_translate("MainWindow", "K"))
        self.lampe_n.setText(_translate("MainWindow", "N"))
        self.lampe_w.setText(_translate("MainWindow", "W"))
        self.lampe_z.setText(_translate("MainWindow", "Z"))
        self.lettre_q.setText(_translate("MainWindow", "Q"))
        self.lettre_w.setText(_translate("MainWindow", "W"))
        self.lettre_e.setText(_translate("MainWindow", "E"))
        self.lettre_r.setText(_translate("MainWindow", "R"))
        self.lettre_t.setText(_translate("MainWindow", "T"))
        self.lettre_z.setText(_translate("MainWindow", "Z"))
        self.lettre_u.setText(_translate("MainWindow", "U"))
        self.lettre_i.setText(_translate("MainWindow", "I"))
        self.lettre_o.setText(_translate("MainWindow", "O"))
        self.lettre_g.setText(_translate("MainWindow", "G"))
        self.lettre_d.setText(_translate("MainWindow", "D"))
        self.lettre_k.setText(_translate("MainWindow", "K"))
        self.lettre_h.setText(_translate("MainWindow", "H"))
        self.lettre_f.setText(_translate("MainWindow", "F"))
        self.lettre_a.setText(_translate("MainWindow", "A"))
        self.lettre_j.setText(_translate("MainWindow", "J"))
        self.lettre_s.setText(_translate("MainWindow", "S"))
        self.lettre_b.setText(_translate("MainWindow", "B"))
        self.lettre_c.setText(_translate("MainWindow", "C"))
        self.lettre_l.setText(_translate("MainWindow", "L"))
        self.lettre_n.setText(_translate("MainWindow", "N"))
        self.lettre_v.setText(_translate("MainWindow", "V"))
        self.lettre_y.setText(_translate("MainWindow", "Y"))
        self.lettre_p.setText(_translate("MainWindow", "P"))
        self.lettre_x.setText(_translate("MainWindow", "X"))
        self.lettre_m.setText(_translate("MainWindow", "M"))
        self.position_rg.setText(_translate("MainWindow", "Z\nA\nB"))
        self.label_rg.setText(_translate("MainWindow", "ROTOR G"))
        self.btn_rg_s.setText(_translate("MainWindow", "⮟"))
        self.btn_rg_p.setText(_translate("MainWindow", "⮝"))
        self.position_rc.setText(_translate("MainWindow", "Z\nA\nB"))
        self.label_rc.setText(_translate("MainWindow", "ROTOR C"))
        self.btn_rc_s.setText(_translate("MainWindow", "⮟"))
        self.btn_rc_p.setText(_translate("MainWindow", "⮝"))
        self.position_rd.setText(_translate("MainWindow", "Z\nA\nB"))
        self.label_rd.setText(_translate("MainWindow", "ROTOR D"))
        self.btn_rd_s.setText(_translate("MainWindow", "⮟"))
        self.btn_rd_p.setText(_translate("MainWindow", "⮝"))
        self.label_crypte.setText(_translate("MainWindow", " CRYPTÉ"))
        self.label_non_crypte.setText(_translate("MainWindow", "NON CRYPTÉ"))
        self.a_label.setText(_translate("MainWindow", "<html><head/><body><p>A</p></body></html>"))
        self.b_label.setText(_translate("MainWindow", "<html><head/><body><p>B</p></body></html>"))
        self.c_label.setText(_translate("MainWindow", "<html><head/><body><p>C</p></body></html>"))
        self.d_label.setText(_translate("MainWindow", "<html><head/><body><p>D</p></body></html>"))
        self.e_label.setText(_translate("MainWindow", "<html><head/><body><p>E</p></body></html>"))
        self.g_label.setText(_translate("MainWindow", "<html><head/><body><p>G</p></body></html>"))
        self.f_label.setText(_translate("MainWindow", "<html><head/><body><p>F</p></body></html>"))
        self.h_label.setText(_translate("MainWindow", "<html><head/><body><p>H</p></body></html>"))
        self.i_label.setText(_translate("MainWindow", "<html><head/><body><p>I</p></body></html>"))
        self.j_label.setText(_translate("MainWindow", "<html><head/><body><p>J</p></body></html>"))
        self.k_label.setText(_translate("MainWindow", "<html><head/><body><p>K</p></body></html>"))
        self.u_label.setText(_translate("MainWindow", "<html><head/><body><p>U</p></body></html>"))
        self.s_label.setText(_translate("MainWindow", "<html><head/><body><p>S</p></body></html>"))
        self.o_label.setText(_translate("MainWindow", "<html><head/><body><p>O</p></body></html>"))
        self.p_label.setText(_translate("MainWindow", "<html><head/><body><p>P</p></body></html>"))
        self.t_label.setText(_translate("MainWindow", "<html><head/><body><p>T</p></body></html>"))
        self.l_label.setText(_translate("MainWindow", "<html><head/><body><p>L</p></body></html>"))
        self.q_label.setText(_translate("MainWindow", "<html><head/><body><p>Q</p></body></html>"))
        self.r_label.setText(_translate("MainWindow", "<html><head/><body><p>R</p></body></html>"))
        self.v_label.setText(_translate("MainWindow", "<html><head/><body><p>V</p></body></html>"))
        self.m_label.setText(_translate("MainWindow", "<html><head/><body><p>M</p></body></html>"))
        self.n_label.setText(_translate("MainWindow", "<html><head/><body><p>N</p></body></html>"))
        self.w_label.setText(_translate("MainWindow", "<html><head/><body><p>W</p></body></html>"))
        self.x_label.setText(_translate("MainWindow", "<html><head/><body><p>X</p></body></html>"))
        self.label_cablage.setText(_translate("MainWindow", "CÂBLAGE"))
        self.y_label.setText(_translate("MainWindow", "<html><head/><body><p>Y</p></body></html>"))
        self.z_label.setText(_translate("MainWindow", "<html><head/><body><p>Z</p></body></html>"))
        self.btn_reinitialiser.setText(_translate("MainWindow", "REINITIALISER"))
        self.btn_configurer.setText(_translate("MainWindow", "CONFIGURER"))
        

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setFocus()
        
    def keyPressEvent(self, event):
        if event.text().upper() in self.alphabet:
            self.verifier_touche(event.text().upper())

class CustomLineEdit(QtWidgets.QLineEdit):
    def mouseDoubleClickEvent(self, event):
        self.vider_entry()
    
    def vider_entry(self):
        if self.text():
            self.setText("-")
            self.setReadOnly(False)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
